// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8g1EPFWqMG0AZ0Br9grAMM_9m2NlsRl8',
    appId: '1:872676818757:web:d271d9309e375364efc82c',
    messagingSenderId: '872676818757',
    projectId: 'app-engcomp-lista-tarefas',
    authDomain: 'app-engcomp-lista-tarefas.firebaseapp.com',
    storageBucket: 'app-engcomp-lista-tarefas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARbvxVVqd0Ci45Wn6QT_1v79nWxPRI3S8',
    appId: '1:872676818757:android:2ff96ffcb7757156efc82c',
    messagingSenderId: '872676818757',
    projectId: 'app-engcomp-lista-tarefas',
    storageBucket: 'app-engcomp-lista-tarefas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM7IM9y6puS91Ue3MDim3E-vypVXE-AnE',
    appId: '1:872676818757:ios:99c577ffbda30912efc82c',
    messagingSenderId: '872676818757',
    projectId: 'app-engcomp-lista-tarefas',
    storageBucket: 'app-engcomp-lista-tarefas.appspot.com',
    iosClientId: '872676818757-5rhog4594d1kmgqbhi605949ss5ba4gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.appEngcomprListaTarefas',
  );
}
